# Generated by Django 5.1.6 on 2025-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_created_date_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
