# Generated by Django 5.1.6 on 2025-06-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_forum_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
