# Generated by Django 5.1.6 on 2025-06-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_forum_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('date', models.IntegerField()),
                ('mounth', models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.message'),
        ),
        migrations.AddField(
            model_name='student',
            name='favorite_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.TextField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
