# Generated by Django 5.2.3 on 2025-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mounth',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
