# Generated by Django 5.2.3 on 2025-06-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_event_message_reply_student_favorite_project_and_more'),
        ('forum', '0005_userprofile'),
    ]

    operations = [
    ]
