# Generated by Django 5.2.3 on 2025-07-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_variantofvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantofvote',
            name='vote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.vote'),
            preserve_default=False,
        ),
    ]
