# Generated by Django 5.2.3 on 2025-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_variantofvote_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantofvote',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
