# Generated by Django 5.2.3 on 2025-06-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='mounth',
            new_name='month',
        ),
    ]
