# Generated by Django 5.2.3 on 2025-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_rename_mounth_event_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
