# Generated by Django 5.2.3 on 2025-07-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_vote_create_date_vote_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-deadline']},
        ),
    ]
